### ISSUE TITLE
adapter-size missing

### ISSUE THREAD

**Issue by YujieOuO** [hustvl/ControlAR#4]
The "adapter-size" parameter is not found in sample_t2i.py.

python autoregressive/sample/sample_t2i.py \
--vq-ckpt checkpoints/vq/vq_ds16_t2i.pt \
--gpt-ckpt checkpoints/t2i/edge_base.safetensors \
--gpt-model GPT-XL --image-size 512 \
--condition-type lineart --seed 0 --condition-path condition/example/t2i/multigen/girl.jpg \
--prompt 'A girl with blue hair' \
--**adapter-size** base \
--control-strength 0.6

**Comment by YujieOuO** [comment]
I change the default params from "small" to "base" adapter size in gpt_t2i.py and run the sample_t2i.py.
but the result seems not good. Any 

prompt: "a girl with blue hair"
![test_lineart](https://github.com/user-attachments/assets/bd9f0a98-1044-4b29-9c44-4322653ba046)

**Comment by lzm2275965881** [comment]
Thank you very much for pointing out that this is indeed due to a small bug. In order to reduce the gap between the three kinds of edge, we choose to reverse lineart map when we combine them together for training. So we need to add one line to the 129 line of [inference](autoregressive/sample/sample_t2i.py) code: condition_img = 1 - condition_img

**Comment by lzm2275965881** [comment]
> I change the default params from "small" to "base" adapter size in gpt_t2i.py and run the sample_t2i.py. but the result seems not good.
> 
> prompt: "a girl with blue hair" ![test_lineart](https://private-user-images.githubusercontent.com/47097735/395989130-bd9f0a98-1044-4b29-9c44-4322653ba046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM0ODUsIm5iZiI6MTczNDMzMzE4NSwicGF0aCI6Ii80NzA5NzczNS8zOTU5ODkxMzAtYmQ5ZjBhOTgtMTA0NC00YjI5LTljNDQtNDMyMjY1M2JhMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YTg4NjUxOGFlOTkxZDM0NmE3MmMxNDViMTUzZmMyODg2MTg5MzY5M2JkZTAwODMzZGI0NDc2YzVhYzY3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YgMymDJnAWLQ8bREnhO27BBN04e93YRuBagpYNaCISo)

Thank you very much for pointing out that this is indeed due to a small bug. In order to reduce the gap between the three kinds of edge, we choose to reverse lineart map when we combine them together for training. So we need to add one line to the 129 line of autoregressive/sample/sample_t2i.py: condition_img = 1 - condition_img

**Comment by YujieOuO** [comment]
Thanks for your quickly reply and it works！
![test_lineart](https://github.com/user-attachments/assets/b850c475-a40b-4394-9329-abcd0ae099b9)
